spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@40.115.13.141:1521:xe
    username: cmadbora
    password: K0lkata123